services:
  main:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - database.env
      - redis.env
      - secret.env
      - web.env
  database:
    image: postgres:15.1
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "course" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  redis:
    image: bitnami/redis:latest
    env_file:
      - redis.env
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "AUTH", "${REDIS_PASSWORD}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
volumes:
  db:
    driver: "local"